import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BookOpen, GraduationCap, LayoutDashboard, LogOut, Pencil, Plus, Printer, Save, ShieldCheck, Trash2, X } from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:4000/api';
const points = { O: 10, 'A+': 9, A: 8, 'B+': 7, B: 6, C: 5, 'U/RA': 0 };
const grades = Object.keys(points);
const request = (path, options = {}) => fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(localStorage.token ? { Authorization: `Bearer ${localStorage.token}` } : {}) } }).then(async (response) => { const data = await response.json(); if (!response.ok) throw Error(data.message || 'Request failed'); return data; });

function App() {
  const [auth, setAuth] = useState(() => JSON.parse(localStorage.auth || 'null'));
  if (!auth) return <Auth onLogin={(data) => { localStorage.token = data.token; localStorage.auth = JSON.stringify(data); setAuth(data); }} />;
  return <Dashboard auth={auth} logout={() => { localStorage.clear(); setAuth(null); }} />;
}
function Auth({ onLogin }) {
  const [register, setRegister] = useState(false); const [error, setError] = useState('');
  const [form, setForm] = useState({ email: '', password: '', name: '', registerNumber: '', department: 'Computer Science', year: 2, semester: 4, section: 'A' });
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  async function submit(event) { event.preventDefault(); setError(''); try { onLogin(await request(`/auth/${register ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify(form) })); } catch (e) { setError(e.message); } }
  return <main className="auth-shell"><section className="auth-art"><Brand /><div><p className="eyebrow">ACADEMIC RECORDS / 2026</p><h1>Your progress,<br /><em>made visible.</em></h1><p className="muted">A clearer way to manage grades, credits, and the journey behind every result.</p></div><p className="quote">“Education is not preparation for life; education is life itself.”<small>— John Dewey</small></p></section><section className="auth-panel"><p className="eyebrow">WELCOME BACK</p><h2>{register ? 'Create your student profile' : 'Sign in to your records'}</h2><p className="muted">{register ? 'After signup, you will enter marks for your selected semester.' : 'Access your academic dashboard.'}</p><form onSubmit={submit}>{register && <><Field name="name" label="Full name" value={form.name} onChange={update} placeholder="Arjun Mehta" /><Field name="registerNumber" label="Register number" value={form.registerNumber} onChange={update} placeholder="24CSE041" /><div className="form-grid"><Field name="year" label="Year" type="number" min="1" max="6" value={form.year} onChange={update} /><Field name="semester" label="Semester" type="number" min="1" max="8" value={form.semester} onChange={update} /></div></>}<Field name="email" label="Email address" type="email" value={form.email} onChange={update} placeholder="you@college.edu" /><Field name="password" label="Password" type="password" value={form.password} onChange={update} placeholder="••••••••" />{error && <div className="error">{error}</div>}<button className="primary full">{register ? 'Create account & enter marks' : 'Sign in'} <span>→</span></button></form><button className="link-button" onClick={() => setRegister(!register)}>{register ? 'Already have an account? Sign in' : 'New student? Create an account'}</button><p className="demo-note">Demo: <b>student@marksheet.dev</b> / Student@123</p></section></main>;
}
function Field({ label, ...props }) { return <label>{label}<input required {...props} /></label>; }
function Brand() { return <div className="brand-mark"><GraduationCap size={22} /> mark<span>sheet</span></div>; }
function Dashboard({ auth, logout }) {
  const teacher = auth.role === 'teacher'; const [page, setPage] = useState('overview'); const [semester, setSemester] = useState(Number(auth.profile?.semester) || 4); const profile = auth.profile;
  return <div className="app-shell"><aside><Brand /><div className="side-label">{teacher ? 'ADMIN CONSOLE' : 'STUDENT PORTAL'}</div><nav><button className={page === 'overview' ? 'active' : ''} onClick={() => setPage('overview')}><LayoutDashboard size={18} /> Overview</button><button className={page === 'marksheet' ? 'active' : ''} onClick={() => setPage('marksheet')}><BookOpen size={18} /> My marksheet</button>{teacher && <button className={page === 'subjects' ? 'active' : ''} onClick={() => setPage('subjects')}><ShieldCheck size={18} /> Subjects & credits</button>}</nav><div className="side-bottom"><div className="profile-mini"><div className="avatar">{profile?.name?.[0] || 'A'}</div><div><b>{profile?.name || auth.profile?.name}</b><small>{teacher ? 'Teacher / Admin' : profile?.registerNumber}</small></div></div><button className="logout" onClick={logout}><LogOut size={16} /> Sign out</button></div></aside><main className="content"><header><div><p className="eyebrow">{teacher ? 'ADMIN CONSOLE' : 'STUDENT PORTAL'} / 2026</p><h1>{page === 'subjects' ? 'Subjects & credits' : page === 'marksheet' ? 'My marksheet' : `Good morning, ${(profile?.name || '').split(' ')[0]}.`}</h1></div><div className="header-actions"><span className="status-dot">System operational</span><div className="avatar">{profile?.name?.[0] || 'A'}</div></div></header>{page === 'subjects' ? <Subjects /> : page === 'marksheet' ? <Marksheet profile={profile} /> : <Overview teacher={teacher} semester={semester} setSemester={setSemester} />}</main></div>;
}
function Overview({ teacher, semester, setSemester }) {
  const [data, setData] = useState(null); const [cumulative, setCumulative] = useState(null); const [values, setValues] = useState({}); const [message, setMessage] = useState('');
  useEffect(() => { if (!teacher) { request(`/grades?semester=${semester}`).then((result) => { setData(result); setValues(Object.fromEntries(result.rows.map((row) => [row.subject._id, row.grade]))); }); request('/results').then((result) => setCumulative(result.cumulative)); } }, [semester, teacher]);
  if (teacher) return <div className="empty-state"><ShieldCheck size={32} /><h2>Welcome to the control room</h2><p>Manage official subject credits and review student academic records.</p></div>;
  async function save() { try { await request('/grades', { method: 'PUT', body: JSON.stringify({ grades: Object.entries(values).map(([subject, grade]) => ({ subject, grade })) }) }); setMessage('Grades saved successfully'); setData(await request(`/grades?semester=${semester}`)); } catch (e) { setMessage(e.message); } }
  return <><div className="welcome-line"><div><p className="eyebrow">NEXT STEP</p><p className="muted">Enter a grade for each subject, then calculate your weighted SGPA.</p></div><select value={semester} onChange={(e) => setSemester(e.target.value)}><option value="4">Semester 04</option><option value="3">Semester 03</option><option value="2">Semester 02</option><option value="1">Semester 01</option></select></div><div className="stat-grid"><Stat label="Current SGPA" value={data?.result.sgpa?.toFixed(2) || '—'} note="Calculated from saved grades" accent="orange" /><Stat label="Overall CGPA" value={cumulative?.cgpa?.toFixed(2) || '—'} note="Weighted completed semesters" accent="green" /><Stat label="Current semester" value={`0${semester}`} note="B.Tech · Year 2" accent="blue" /><Stat label="Credits earned" value={data?.result.credits || '—'} note="This semester" accent="yellow" /></div><section className="panel"><div className="panel-heading"><div><p className="eyebrow">SEMESTER {String(semester).padStart(2, '0')} / 2026</p><h2>Enter your marks</h2></div><span className="read-only"><ShieldCheck size={14} /> Credits set by faculty</span></div><Table rows={data?.rows || []} values={values} setValues={setValues} /><div className="panel-footer"><span className={message.includes('success') ? 'success' : 'muted'}>{message}</span><button className="primary" onClick={save}><Save size={16} /> Save grades & calculate SGPA</button></div></section></>;
}
function Table({ rows, values, setValues }) { return <div className="table-wrap"><table><thead><tr><th>Subject</th><th>Code</th><th>Credits</th><th>Your grade</th><th>Points</th></tr></thead><tbody>{rows.map(({ subject }) => <tr key={subject._id}><td><b>{subject.name}</b></td><td className="code">{subject.code}</td><td><span className="credit-pill">{subject.credits} cr</span></td><td><select className="grade-select" value={values[subject._id] || ''} onChange={(e) => setValues({ ...values, [subject._id]: e.target.value })}><option value="">Select grade</option>{grades.map((grade) => <option key={grade}>{grade}</option>)}</select></td><td className="points">{points[values[subject._id]] || '—'}</td></tr>)}</tbody></table></div>; }
function Stat({ label, value, note, accent }) { return <div className={`stat-card ${accent}`}><div className="stat-label">{label}<span>✦</span></div><strong>{value}</strong><small>{note}</small></div>; }
function Subjects() { const [items, setItems] = useState([]); const [editing, setEditing] = useState(null); const blank = { code: '', name: '', semester: 4, department: 'Computer Science', credits: 3 }; const [form, setForm] = useState(blank); const load = () => request('/admin/subjects').then(setItems); useEffect(load, []); async function submit(e) { e.preventDefault(); await request(editing ? `/admin/subjects/${editing}` : '/admin/subjects', { method: editing ? 'PUT' : 'POST', body: JSON.stringify(form) }); setForm(blank); setEditing(null); load(); } function edit(item) { setEditing(item._id); setForm({ code: item.code, name: item.name, semester: item.semester, department: item.department, credits: item.credits }); } const Action = editing ? Pencil : Plus; return <div className="admin-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">FACULTY CONTROL</p><h2>{editing ? 'Edit subject' : 'Add a subject'}</h2></div>{editing && <button className="icon-button" onClick={() => setEditing(null)}><X size={18} /></button>}</div><form className="subject-form" onSubmit={submit}><Field label="Subject code" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value.toUpperCase() })} placeholder="CS405" /><Field label="Subject name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Computer Networks" /><div className="form-grid"><Field label="Semester" type="number" value={form.semester} onChange={(e) => setForm({ ...form, semester: e.target.value })} /><Field label="Credits" type="number" step="0.5" value={form.credits} onChange={(e) => setForm({ ...form, credits: e.target.value })} /></div><Field label="Department" value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })} /><button className="primary full"><Action size={16} /> {editing ? 'Update subject' : 'Add subject'}</button></form></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">OFFICIAL CATALOG</p><h2>Managed subjects</h2></div><span className="count-pill">{items.length} subjects</span></div>{items.map((item) => <div className="subject-row" key={item._id}><div><b>{item.code}</b><span>{item.name}</span></div><span className="credit-pill">{item.credits} credits</span><button className="icon-button" onClick={() => edit(item)}><Pencil size={16} /></button><button className="icon-button danger" onClick={async () => { await request(`/admin/subjects/${item._id}`, { method: 'DELETE' }); load(); }}><Trash2 size={16} /></button></div>)}</section></div>; }
function Marksheet({ profile }) { const [data, setData] = useState(null); useEffect(() => { request('/results').then(setData); }, []); return <section className="panel marksheet"><div className="marksheet-top"><div><p className="eyebrow">OFFICIAL ACADEMIC RECORD</p><h2>Student marksheet</h2><p className="muted">{profile?.name} · {profile?.registerNumber} · {profile?.department}</p></div><button className="secondary" onClick={() => window.print()}><Printer size={16} /> Print / download</button></div>{data?.semesters.map((semester) => <div className="result-block" key={semester.semester}><div className="result-heading"><h3>Semester {String(semester.semester).padStart(2, '0')}</h3><strong>SGPA {semester.result.sgpa.toFixed(2)}</strong></div><table><thead><tr><th>Code</th><th>Subject</th><th>Credits</th><th>Grade</th><th>Points</th></tr></thead><tbody>{semester.rows.filter((row) => row.grade).map((row) => <tr key={row.subject._id}><td className="code">{row.subject.code}</td><td>{row.subject.name}</td><td>{row.subject.credits}</td><td><b>{row.grade}</b></td><td>{points[row.grade]}</td></tr>)}</tbody></table></div>)}{!data?.semesters.length && <div className="empty-state"><BookOpen size={32} /><h2>Your marksheet will appear here</h2><p>Enter and save grades from Overview to generate your record.</p></div>}<div className="cgpa-banner"><span>Overall CGPA</span><strong>{data?.cumulative.cgpa?.toFixed(2) || '—'}</strong><small>Weighted across completed semesters</small></div></section>; }

createRoot(document.getElementById('root')).render(<App />);
